
[build]
  command = "npm run prebuild && rm -rf .next .cache && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_PNPM = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
