import fs from "fs/promises";
import path from "path";

const generatedFilePath = path.resolve(
  process.cwd(),
  "src/lib/data/_generated.ts",
);

async function createGeneratedFile() {
  const content = `// This file is auto-generated by scripts/build-data.mjs
// To re-enable data compilation, restore the original content of the script.

import { allData } from "./index";

export { allData };
`;

  try {
    await fs.writeFile(generatedFilePath, content, "utf-8");
    console.log("✅ Successfully created redirect file: _generated.ts");
  } catch (error) {
    console.error("❌ Error creating _generated.ts file:", error);
    process.exit(1);
  }
}

async function main() {
  console.log("🚀 Starting data linking process...");
  await createGeneratedFile();
  console.log("✅ Data linking process completed successfully!");
}

main();
