// This file is auto-generated by scripts/build-data.mjs
// To re-enable data compilation, restore the original content of the script.

import aboutContent from "./about/content.json";
import contactContent from "./contact/content.json";
import contributorsList from "./contributors/list.json";
import coursesList from "./courses/list.json";
import deadlinesList from "./deadlines/list.json";
import linksList from "./links/list.json";
import navigationLinks from "./navigation/links.json";
import questionBankCards from "./question-bank/cards.json";
import schedulesAdmission from "./schedules/admission.json";
import schedulesApplication from "./schedules/application.json";
import schedulesGeneral from "./schedules/general.json";
import schedulesOthers from "./schedules/others.json";
import testPapersList from "./test-papers/list.json";
import CalendarInfo from "./deadlines/list.json";
import calculatorContent from "./calculator/content.json";

// University data imports
import publicUniversities from "./universities/public-universities.json";
import privateUniversities from "./universities/private-universities.json";

import duInfo from "./universities/du/info.json";
import ruInfo from "./universities/ru/info.json";
import gstInfo from "./universities/gst/info.json";

type University = (typeof publicUniversities)[0];

const universityDetails: Record<string, any> = {
  du: duInfo,
  ru: ruInfo,
  gst: gstInfo,
};

const allUniversities = [...publicUniversities, ...privateUniversities].map(
  (uni: University) => {
    const details = universityDetails[uni.id];
    if (details) {
      return { ...uni, ...details };
    }
    return {
      ...uni,
      admissionInfo: {},
      historyAndMap: {},
      links: [],
      questionBanks: {},
      subjects: {},
    };
  },
);

export const allData = {
  aboutContent,
  contactContent,
  contributorsList,
  coursesList,
  deadlinesList,
  linksList,
  navigationLinks,
  questionBankCards,
  schedulesAdmission,
  schedulesApplication,
  schedulesGeneral,
  schedulesOthers,
  testPapersList,
  universities: allUniversities,
  CalendarInfo,
  calculatorContent,
};
