// This file is auto-generated by scripts/build-data.mjs
// To re-enable data compilation, restore the original content of the script.

import content from "./content.json";
import contributorsList from "./contributors.json";
import specialContributorsList from "./special-contributors.json";
import deadlinesList from "./deadlines.json";
import linksList from "./links.json";
import questionBankCards from "./question-bank.json";
import schedules from "./schedules.json";
import testPapersList from "./test-papers.json";
import CalendarInfo from "./deadlines.json";
import placeholderImagesData from "./placeholder-images.json";
import footerData from "./footer.json";

// University data imports
import publicUniversities from "./universities/public-universities.json";
import privateUniversities from "./universities/private-universities.json";

import duInfo from "./universities/du/info.json";
import ruInfo from "./universities/ru/info.json";
import gstInfo from "./universities/gst/info.json";
import agriInfo from "./universities/agri/info.json";
import mistInfo from "./universities/mist/info.json";

type University = (typeof publicUniversities)[0];

export type ImagePlaceholder = {
  id: string;
  description: string;
  imageUrl: string;
  imageHint: string;
};

const universityDetails: Record<string, any> = {
  du: duInfo,
  ru: ruInfo,
  gst: gstInfo,
  agri: agriInfo,
  mist: mistInfo,
};

const allUniversities = [...publicUniversities, ...privateUniversities].map(
  (uni: University) => {
    const details = universityDetails[uni.id];
    if (details) {
      return { ...uni, ...details };
    }
    return {
      ...uni,
      admissionInfo: {},
      historyAndMap: {},
      links: [],
      questionBanks: {},
      subjects: {},
    };
  },
);

export const allData = {
  aboutContent: content.about,
  contactContent: content.contact,
  contributorsList,
  specialContributorsList,
  deadlinesList,
  linksList,
  questionBankCards,
  schedulesAdmission: schedules.admission,
  schedulesApplication: schedules.application,
  schedulesGeneral: schedules.general,
  schedulesOthers: schedules.others,
  testPapersList,
  universities: allUniversities,
  CalendarInfo,
  calculatorContent: content.calculator,
  placeholderImages: placeholderImagesData as ImagePlaceholder[],
  footer: footerData,
};
