// This file is auto-generated by scripts/build-data.mjs. Do not edit manually.

export const allUniversityData = [
  {
    "nameBn": "ঢাকা বিশ্ববিদ্যালয়",
    "nameEn": "University of Dhaka",
    "shortName": "DU",
    "id": "du",
    "category": [
      "সাধারণ"
    ],
    "description": "দেশের শীর্ষস্থানীয় গবেষণাধর্মী সরকারি বিশ্ববিদ্যালয়।",
    "link": "/du",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/DU.png",
    "admissionInfo": {
      "title": "ভর্তি তথ্য (HSC-24)",
      "apply": {
        "title": "আবেদন",
        "startDate": "০৪ নভেম্বর, ২০২৪ (দুপুর ১২টা থেকে)",
        "endDate": "২৫ নভেম্বর, ২০২৪ (রাত ১১.৫৯টা পর্যন্ত)",
        "fees": [
          {
            "unit": "ক, খ, গ, চ ইউনিট",
            "amount": "১০৫০৳"
          },
          {
            "unit": "আইবিএ ইউনিট",
            "amount": "১৫০০৳"
          }
        ],
        "helpfulLinks": [
          {
            "label": "আবেদনের ধাপসমূহ",
            "url": "https://t.me/Study_on_Telegram/13209"
          },
          {
            "label": "সচিত্র আবেদন প্রক্রিয়া",
            "url": "https://t.me/Study_on_Telegram/13206"
          }
        ],
        "link": "https://admission.eis.du.ac.bd/",
        "qualificationTitle": "আবেদনের যোগ্যতাঃ",
        "sscBatch": "2019-2022",
        "hscBatch": "2024",
        "secondTime": "নেই"
      },
      "unitRequirements": {
        "title": "ইউনিট ও বিভাগ ভিত্তিক শর্ত",
        "units": [
          {
            "name": "ক",
            "departments": [
              {
                "name": "বিজ্ঞান বিভাগ",
                "requirement": "SSC ও HSC তে চতুর্থ বিষয় সহ ন্যূনতম GPA-3.5 এবং SSC ও HSC মিলে মোট ন্যূনতম GPA-8.0"
              },
              {
                "name": "অন্যান্য বিভাগ",
                "requirement": "SSC ও HSC তে চতুর্থ বিষয় সহ ন্যূনতম GPA-3.0 এবং SSC ও HSC মিলে মোট ন্যূনতম GPA-7.5"
              }
            ]
          },
          {
            "name": "খ",
            "departments": [
              {
                "name": "মানবিক ও ব্যবসা বিভাগ",
                "requirement": "SSC ও HSC তে চতুর্থ বিষয় সহ ন্যূনতম GPA-3.0 এবং SSC ও HSC মিলে মোট ন্যূনতম GPA-7.5"
              },
              {
                "name": "বিজ্ঞান বিভাগ",
                "requirement": "SSC ও HSC তে চতুর্থ বিষয় সহ ন্যূনতম GPA-3.5 এবং SSC ও HSC মিলে মোট ন্যূনতম GPA-8.0"
              }
            ]
          },
          {
            "name": "গ",
            "departments": [
              {
                "name": "মানবিক ও ব্যবসা বিভাগ",
                "requirement": "SSC ও HSC তে চতুর্থ বিষয় সহ ন্যূনতম GPA-3.0 এবং SSC ও HSC মিলে মোট ন্যূনতম GPA-7.5"
              },
              {
                "name": "বিজ্ঞান বিভাগ",
                "requirement": "SSC ও HSC তে চতুর্থ বিষয় সহ ন্যূনতম GPA-3.5 এবং SSC ও HSC মিলে মোট ন্যূনতম GPA-8.0"
              }
            ]
          },
          {
            "name": "চ",
            "departments": [
              {
                "name": "যেকোনো বিভাগ",
                "requirement": "SSC ও HSC তে চতুর্থ বিষয় সহ ন্যূনতম GPA-3.0 এবং SSC ও HSC মিলে মোট ন্যূনতম GPA-6.5"
              }
            ]
          },
          {
            "name": "IBA",
            "departments": [
              {
                "name": "যেকোনো বিভাগ",
                "requirement": "SSC ও HSC তে চতুর্থ বিষয় সহ ন্যূনতম GPA-3.5 এবং SSC ও HSC মিলে মোট ন্যূনতম GPA-8.0"
              }
            ]
          }
        ]
      },
      "improvementPolicy": {
        "title": "ইমপ্রুভমেন্ট ও পরবর্তী ব্যাচের পরীক্ষা",
        "details": "<b>দুটি শর্ত পূরণ করে একজন শিক্ষার্থী পরবর্তী ব্যাচের সাথে ঢাকা বিশ্ববিদ্যালয়ে পরীক্ষা দিতে পারে:<br/><br/>১।</b> ঢাকা বিশ্ববিদ্যালয় বা এর অধিভুক্ত কোনো কলেজে আবেদন না করা।<br/><b>২।</b> পরবর্তী ব্যাচের সাথে HSC ইমপ্রুভমেন্ট পরীক্ষা দেওয়া।<br/><br/><b><u>উদাহরণ:</u></b> একজন HSC-24 ব্যাচের শিক্ষার্থী যদি ঢাবিতে আবেদন না করে এবং HSC-25 ব্যাচের সাথে ইমপ্রুভমেন্ট দেয়, তবে সে HSC-25 ব্যাচের সাথে পরীক্ষা দিতে পারবে।"
      },
      "admitCard": {
        "title": "প্রবেশপত্র",
        "startDate": "২৩ ডিসেম্বর, ২০২৪",
        "endDate": "পরীক্ষা শুরুর ১ ঘণ্টা পূর্ব পর্যন্ত",
        "link": "https://admission.eis.du.ac.bd/",
        "note": "প্রবেশপত্রে শুধু পরীক্ষার অঞ্চল উল্লেখ থাকে। পরীক্ষার কেন্দ্র, বিল্ডিং ও রুম নম্বর সাধারণত পরীক্ষার ৪৮-৭২ ঘণ্টা আগে ওয়েবসাইটে প্রকাশ করা হয়।"
      },
      "examDate": {
        "title": "পরীক্ষার সময়কাল",
        "dates": [
          {
            "unit": "ক",
            "date": "১৫ ফেব্রুয়ারী"
          },
          {
            "unit": "খ",
            "date": "২৫ জানুয়ারী"
          },
          {
            "unit": "গ",
            "date": "০৮ ফেব্রুয়ারী"
          },
          {
            "unit": "চ",
            "date": "০৪ জানুয়ারী"
          },
          {
            "unit": "IBA",
            "date": "০৩ জানুয়ারী"
          }
        ],
        "note": {
          "text": "অ্যাডমিশন ক্যালেন্ডার",
          "link": "https://mnr.world/ac/"
        }
      },
      "examCenter": {
        "title": "ভর্তি পরীক্ষার কেন্দ্র",
        "location": "বিভাগীয় শহরে",
        "locationLink": "https://t.me/Study_on_Telegram/13199",
        "note": "'চ' ইউনিট (চারুকলা) এবং IBA-এর পরীক্ষা শুধু ঢাকায় অনুষ্ঠিত হবে। বাকি সব ইউনিটের পরীক্ষা বিভাগীয় শহরে হবে।"
      },
      "generalInfo": {
        "title": "মানবন্টন ও অন্যান্য তথ্য",
        "points": [
          {
            "label": "সিলেবাস",
            "value": "সংক্ষিপ্ত"
          },
          {
            "label": "সেকেন্ড টাইম",
            "value": "নেই"
          },
          {
            "label": "নেগেটিভ মার্কিং",
            "value": "প্রতি ভুলের জন্য ০.২৫ নম্বর কাটা যাবে"
          },
          {
            "label": "ক্যালকুলেটর",
            "value": "ব্যবহার করা যাবে না"
          }
        ]
      },
      "result": {
        "title": "ভর্তি পরীক্ষার ফলাফল",
        "date": "ভর্তি পরীক্ষার ৪ সপ্তাহের মধ্যে",
        "link": "https://admission.eis.du.ac.bd/"
      }
    },
    "historyAndMap": {
      "history": {
        "title": "একনজরে ঢাকা বিশ্ববিদ্যালয়",
        "paragraphs": [
          "ঢাকা বিশ্ববিদ্যালয় (ঢাবি) বাংলাদেশের সর্বপ্রথম এবং অন্যতম প্রধান উচ্চশিক্ষা প্রতিষ্ঠান, যা ১৯২১ সালের ১ জুলাই প্রতিষ্ঠিত হয়। এটি ব্রিটিশ ভারতের অক্সব্রিজ মডেল অনুসরণে গঠিত হয়েছিল এবং শুরুতে তিনটি অনুষদ (কলা, বিজ্ঞান ও আইন) এবং ১২টি বিভাগ নিয়ে যাত্রা শুরু করে।",
          "১৯০৫ সালে বঙ্গভঙ্গের মাধ্যমে পূর্ব বাংলা ও আসাম নিয়ে একটি নতুন প্রদেশ গঠিত হয়, যার রাজধানী ছিল ঢাকা। এই প্রক্রিয়ায় মুসলিম সমাজের মধ্যে শিক্ষার প্রসার ঘটে। তবে ১৯১১ সালে বঙ্গভঙ্গ রদের ফলে পূর্ব বাংলার মুসলিম সমাজের মধ্যে উচ্চশিক্ষার সুযোগ হ্রাস পায়। এই প্রেক্ষাপটে, ১৯১২ সালের ২১ জানুয়ারি ভারতের ভাইসরয় লর্ড হার্ডিঞ্জ ঢাকায় সফরকালে একটি বিশ্ববিদ্যালয় প্রতিষ্ঠার প্রতিশ্রুতি দেন।",
          "এরপর ব্যারিস্টার রবার্ট নাথানের নেতৃত্বে নাথান কমিশন গঠিত হয় এবং ১৯১৩ সালে তার রিপোর্ট অনুমোদন পায়। বর্তমানে ঢাকা বিশ্ববিদ্যালয় ৪৬,০০০-এরও বেশি শিক্ষার্থী এবং ২,০০০-এরও বেশি শিক্ষক নিয়ে বাংলাদেশের বৃহত্তম পাবলিক গবেষণা বিশ্ববিদ্যালয়। এটি দেশের শিক্ষা, সংস্কৃতি এবং মুক্ত চিন্তার বিকাশে গুরুত্বপূর্ণ ভূমিকা পালন করে চলেছে।"
        ],
        "source": {
          "label": "উৎস",
          "links": [
            {
              "text": "উইকিপিডিয়া প্রতিবেদন (ঢাকা বিশ্ববিদ্যালয়)",
              "url": "https://bn.wikipedia.org/wiki/%E0%A6%A2%E0%A6%BE%E0%A6%95%E0%A6%BE_%E0%A6%AC%E0%A6%BF%E0%A6%B6%E0%A7%8D%E0%A6%AC%E0%A6%AC%E0%A6%BF%E0%A6%A6%E0%A7%8D%E0%A6%AF%E0%A6%BE%E0%A6%B2%E0%A6%AF%E0%A6%BC"
            }
          ]
        }
      },
      "mapLocations": {
        "title": "ক্যাম্পাসের গুগল ম্যাপ লোকেশন",
        "categories": [
          {
            "name": "মসজিদ",
            "locations": [
              {
                "name": "মুসা খান মসজিদ",
                "url": "https://maps.app.goo.gl/A5Pt2z5yceEQ641y7?g_st=atm"
              }
            ]
          },
          {
            "name": "প্রশাসনিক ভবন",
            "locations": [
              {
                "name": "রেজিস্ট্রার বিল্ডিং",
                "url": "https://maps.app.goo.gl/your-link-here"
              }
            ]
          }
        ]
      }
    },
    "links": [
      [
        {
          "href": "#Circular",
          "label": "সার্কুলার"
        },
        {
          "href": "/question-bank?tab=du",
          "label": "প্রশ্নব্যাংক"
        }
      ],
      [
        {
          "href": "https://www.du.ac.bd/",
          "label": "মূল ওয়েবসাইট",
          "target": "_blank",
          "rel": "noreferrer noopener"
        },
        {
          "href": "https://admission.eis.du.ac.bd/bn/408b7c8ad06e4d9954fa2d948a01f508",
          "label": "ভর্তি ওয়েবসাইট",
          "target": "_blank",
          "rel": "noreferrer noopener"
        }
      ],
      [
        {
          "href": "https://admission.eis.du.ac.bd/bn/408b7c8ad06e4d9954fa2d948a01f508",
          "label": "আবেদন <b>|</b> প্রবেশপত্র <b>|</b> ফলাফল",
          "target": "_blank",
          "rel": "noreferrer noopener",
          "colSpan": 2
        }
      ],
      [
        {
          "href": "https://collegeadmission.eis.du.ac.bd/en/b45de047fde9788c53fradae3cfe8e88dc02",
          "label": "অধিভুক্ত কলেজ ভর্তি",
          "target": "_blank",
          "rel": "noreferrer noopener",
          "colSpan": 2
        }
      ]
    ],
    "questionBanks": {
      "duUnitA": [
        {
          "title": "সালভিত্তিক প্রশ্নব্যাংক",
          "items": [
            {
              "links": [
                {
                  "text": "আসপেক্ট “ক” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/PDFHour/10357"
                },
                {
                  "text": "উদ্ভাস “ক” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/PDFHour/10357"
                },
                {
                  "text": "জয়কলি “ক” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/PDFHour/10357"
                },
                {
                  "text": "UCC “ক” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/PDFHour/10357"
                },
                {
                  "text": "ACS “ক” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/PDFHour/10357"
                }
              ]
            },
            {
              "title": "সকল সালের প্রশ্ন একত্রে",
              "links": [
                {
                  "text": "Question of 1995-96",
                  "url": "https://t.me/PDFHour/10297"
                },
                {
                  "text": "Question of 1996-97",
                  "url": "https://t.me/PDFHour/10298"
                },
                {
                  "text": "Question of 1998-99",
                  "url": "https://t.me/PDFHour/10299"
                },
                {
                  "text": "Question of 1999-00",
                  "url": "https://t.me/PDFHour/10300"
                },
                {
                  "text": "Question of 2000-01",
                  "url": "https://t.me/PDFHour/10303?single"
                },
                {
                  "text": "Question of 2001-02",
                  "url": "https://t.me/PDFHour/10305?single"
                },
                {
                  "text": "Question of 2002-03",
                  "url": "https://t.me/PDFHour/10307?single"
                },
                {
                  "text": "Question of 2003-04",
                  "url": "https://t.me/PDFHour/10309?single"
                },
                {
                  "text": "Question of 2004-05",
                  "url": "https://t.me/PDFHour/10311?single"
                },
                {
                  "text": "Question of 2005-06",
                  "url": "https://t.me/PDFHour/10313?single"
                },
                {
                  "text": "Question of 2006-07",
                  "url": "https://t.me/PDFHour/10315?single"
                },
                {
                  "text": "Question of 2007-08",
                  "url": "https://t.me/PDFHour/10317?single"
                },
                {
                  "text": "Question of 2008-09",
                  "url": "https://t.me/PDFHour/10319?single"
                },
                {
                  "text": "Question of 2009-10",
                  "url": "https://t.me/PDFHour/10321?single"
                },
                {
                  "text": "Question of 2010-11",
                  "url": "https://t.me/PDFHour/10323?single"
                },
                {
                  "text": "Question of 2011-12",
                  "url": "https://t.me/PDFHour/10325?single"
                },
                {
                  "text": "Question of 2012-13",
                  "url": "https://t.me/PDFHour/10328?single"
                },
                {
                  "text": "Question of 2013-14",
                  "url": "https://t.me/PDFHour/10331?single"
                },
                {
                  "text": "Question of 2014-15",
                  "url": "https://t.me/PDFHour/10334?single"
                },
                {
                  "text": "Question of 2015-16",
                  "url": "https://t.me/PDFHour/10337?single"
                },
                {
                  "text": "Question of 2016-17",
                  "url": "https://t.me/PDFHour/10340?single"
                },
                {
                  "text": "Question of 2017-18",
                  "url": "https://t.me/PDFHour/10343?single"
                },
                {
                  "text": "Question of 2018-19",
                  "url": "https://t.me/PDFHour/10346?single"
                },
                {
                  "text": "Question of 2019-20",
                  "url": "https://t.me/PDFHour/10349?single"
                },
                {
                  "text": "Question of 2020-21",
                  "url": "https://t.me/PDFHour/10350"
                },
                {
                  "text": "Question of 2021-22",
                  "url": "https://t.me/PDFHour/10352?single"
                },
                {
                  "text": "Question of 2022-23",
                  "url": "https://t.me/PDFHour/10355?single"
                },
                {
                  "text": "Question of 2023-24",
                  "url": "https://t.me/PDFHour/10356"
                }
              ]
            }
          ]
        },
        {
          "title": "অধ্যায়ভিত্তিক প্রশ্নব্যাংক",
          "items": [
            {
              "links": [
                {
                  "text": "রেটিনা ঢাবি “ক” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/PDFHour/10285"
                }
              ]
            },
            {
              "title": "সহায়ক বই",
              "links": [
                {
                  "text": "উদ্ভাস ভার্সিটি “ক” প্রশ্নব্যাংক",
                  "url": "https://t.me/PDFHour/10214"
                },
                {
                  "text": "উদ্ভাস ভার্সিটি “ক” প্রিপারেশন বুক",
                  "url": "https://t.me/PDFHour/10478"
                }
              ]
            }
          ]
        },
        {
          "title": "মডেল টেস্ট",
          "items": [
            {
              "links": [
                {
                  "text": "জয়কলি ঢাবি “ক” ইউনিট মডেল টেস্ট",
                  "url": "https://t.me/PDFHour/"
                }
              ]
            },
            {
              "title": "সহায়ক বই",
              "links": [
                {
                  "text": "জয়কলি ভার্সিটি “ক” মডেল টেস্ট",
                  "url": "https://t.me/PDFHour/"
                },
                {
                  "text": "উদ্ভাস ভার্সিটি “ক” প্র্যাকটিস বুক",
                  "url": "https://t.me/PDFHour/"
                }
              ]
            }
          ]
        },
        {
          "title": "সাজেশন",
          "items": [
            {
              "links": [
                {
                  "text": "BOB ঢাবি “ক” ইউনিট সাজেশন (MCQ ও লিখিত)",
                  "url": "https://t.me/PDFHour/"
                }
              ]
            }
          ]
        }
      ],
      "duUnitB": [
        {
          "title": "সালভিত্তিক প্রশ্নব্যাংক",
          "items": [
            {
              "links": [
                {
                  "text": "পানকৌড়ি “খ” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/PDFHour/10394"
                },
                {
                  "text": "আসপেক্ট “খ” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/PDFHour/10394"
                },
                {
                  "text": "জয়কলি “খ” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/PDFHour/10394"
                },
                {
                  "text": "UCC “খ” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/PDFHour/10394"
                }
              ]
            },
            {
              "title": "সকল সালের প্রশ্ন একত্রে",
              "links": [
                {
                  "text": "Question of 2000-01",
                  "url": "https://t.me/PDFHour/10359"
                },
                {
                  "text": "Question of 2001-02",
                  "url": "https://t.me/PDFHour/10360"
                },
                {
                  "text": "Question of 2002-03",
                  "url": "https://t.me/PDFHour/10361"
                },
                {
                  "text": "Question of 2003-04",
                  "url": "https://t.me/PDFHour/10362"
                },
                {
                  "text": "Question of 2004-05",
                  "url": "https://t.me/PDFHour/10363"
                },
                {
                  "text": "Question of 2005-06",
                  "url": "https://t.me/PDFHour/10364"
                },
                {
                  "text": "Question of 2006-07",
                  "url": "https://t.me/PDFHour/10365"
                },
                {
                  "text": "Question of 2007-08",
                  "url": "https://t.me/PDFHour/10366"
                },
                {
                  "text": "Question of 2008-09",
                  "url": "https://t.me/PDFHour/10367"
                },
                {
                  "text": "Question of 2009-10",
                  "url": "https://t.me/PDFHour/10368"
                },
                {
                  "text": "Question of 2010-11",
                  "url": "https://t.me/PDFHour/10370?single"
                },
                {
                  "text": "Question of 2011-12",
                  "url": "https://t.me/PDFHour/10372?single"
                },
                {
                  "text": "Question of 2012-13",
                  "url": "https://t.me/PDFHour/10374?single"
                },
                {
                  "text": "Question of 2013-14",
                  "url": "https://t.me/PDFHour/10376?single"
                },
                {
                  "text": "Question of 2014-15",
                  "url": "https://t.me/PDFHour/10378?single"
                },
                {
                  "text": "Question of 2015-16",
                  "url": "https://t.me/PDFHour/10380?single"
                },
                {
                  "text": "Question of 2016-17",
                  "url": "https://t.me/PDFHour/10382?single"
                },
                {
                  "text": "Question of 2017-18",
                  "url": "https://t.me/PDFHour/10384?single"
                },
                {
                  "text": "Question of 2018-19",
                  "url": "https://t.me/PDFHour/10386?single"
                },
                {
                  "text": "Question of 2019-20",
                  "url": "https://t.me/PDFHour/10388?single"
                },
                {
                  "text": "Question of 2020-21",
                  "url": "https://t.me/PDFHour/10389"
                },
                {
                  "text": "Question of 2021-22",
                  "url": "https://t.me/PDFHour/10390"
                },
                {
                  "text": "Question of 2022-23",
                  "url": "https://t.me/PDFHour/10391"
                },
                {
                  "text": "Question of 2023-24",
                  "url": "https://t.me/PDFHour/10392"
                },
                {
                  "text": "Question of 2024-25",
                  "url": "https://t.me/PDFHour/10835?single"
                }
              ]
            }
          ]
        },
        {
          "title": "সহায়ক প্রশ্নব্যাংক",
          "items": [
            {
              "links": [
                {
                  "text": "উদ্ভাস “ঘ” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/Study_on_Telegram/2072"
                },
                {
                  "text": "UCC “ঘ” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/Study_on_Telegram/8882"
                }
              ]
            }
          ]
        },
        {
          "title": "সাজেশন",
          "items": [
            {
              "links": [
                {
                  "text": "Written Foundation Book By iEducation",
                  "url": "https://t.me/PDFHour/10731"
                }
              ]
            }
          ]
        }
      ],
      "duUnitC": [
        {
          "title": "সালভিত্তিক প্রশ্নব্যাংক",
          "items": [
            {
              "links": [
                {
                  "text": "ফোকাস “গ” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/Study_on_Telegram/2072"
                },
                {
                  "text": "আইকন “গ” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/Study_on_Telegram/2072"
                },
                {
                  "text": "জয়কলি “গ” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/Study_on_Telegram/2072"
                },
                {
                  "text": "UCC “গ” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/Study_on_Telegram/8882"
                }
              ]
            },
            {
              "title": "সকল সালের প্রশ্ন একত্রে",
              "links": [
                {
                  "text": "Question of 2006-07",
                  "url": "#"
                },
                {
                  "text": "Question of 2007-08",
                  "url": "#"
                },
                {
                  "text": "Question of 2008-09",
                  "url": "#"
                },
                {
                  "text": "Question of 2009-10",
                  "url": "#"
                },
                {
                  "text": "Question of 2010-11",
                  "url": "#"
                },
                {
                  "text": "Question of 2011-12",
                  "url": "#"
                },
                {
                  "text": "Question of 2012-13",
                  "url": "#"
                },
                {
                  "text": "Question of 2013-14",
                  "url": "#"
                },
                {
                  "text": "Question of 2014-15",
                  "url": "#"
                },
                {
                  "text": "Question of 2015-16",
                  "url": "#"
                },
                {
                  "text": "Question of 2016-17",
                  "url": "#"
                },
                {
                  "text": "Question of 2017-18",
                  "url": "#"
                },
                {
                  "text": "Question of 2018-19",
                  "url": "#"
                },
                {
                  "text": "Question of 2019-20",
                  "url": "#"
                },
                {
                  "text": "Question of 2020-21",
                  "url": "#"
                },
                {
                  "text": "Question of 2021-22",
                  "url": "#"
                },
                {
                  "text": "Question of 2022-23",
                  "url": "#"
                },
                {
                  "text": "Question of 2023-24",
                  "url": "#"
                },
                {
                  "text": "Question of 2024-25",
                  "url": "https://t.me/PDFHour/10359"
                }
              ]
            }
          ]
        },
        {
          "title": "অধ্যায়ভিত্তিক প্রশ্নব্যাংক",
          "items": [
            {
              "links": [
                {
                  "text": "টেন মিনিট স্কুল ঢাবি “গ” ইউনিট প্রশ্নব্যাংক",
                  "url": "https://t.me/PDFHour/10285"
                }
              ]
            }
          ]
        }
      ],
      "duUnitCha": [
        {
          "title": "সালভিত্তিক প্রশ্নব্যাংক",
          "items": [
            {
              "links": [
                {
                  "text": "Question of 2023-24",
                  "url": "https://t.me/PDFHour/10638"
                },
                {
                  "text": "Question of 2024-25",
                  "url": "https://t.me/PDFHour/10728"
                }
              ]
            }
          ]
        }
      ],
      "duIBA": [
        {
          "title": "সকল কিছু একসাথে",
          "items": [
            {
              "links": [
                {
                  "text": "DU IBA Question Bank",
                  "url": "https://t.me/Study_on_Telegram/2069"
                },
                {
                  "text": "Dreams IBA Ex. MBA Book",
                  "url": "https://t.me/Study_on_Telegram/2070"
                }
              ]
            }
          ]
        }
      ]
    },
    "subjects": {
      "unitA": [
        {
          "short": "ACCE",
          "fullName": "Applied Chemistry and Chemical Engineering",
          "seat": 60,
          "reviewLink": "https://study.mnr.world/ACCE/"
        },
        {
          "short": "AMT",
          "fullName": "Applied Mathematics",
          "seat": 60,
          "reviewLink": "https://study.mnr.world/AMT/"
        },
        {
          "short": "ASDS",
          "fullName": "Applied Statistics and Data Science",
          "seat": 55,
          "reviewLink": "https://study.mnr.world/ASDS/"
        },
        {
          "short": "BMB",
          "fullName": "Biochemistry and Molecular Biology",
          "seat": 60,
          "reviewLink": "https://study.mnr.world/BMB/"
        },
        {
          "short": "BOT",
          "fullName": "Botany",
          "seat": 70,
          "reviewLink": "https://study.mnr.world/BOT/"
        },
        {
          "short": "BS",
          "fullName": "Biological Science",
          "seat": 19,
          "reviewLink": "https://study.mnr.world/BS/"
        },
        {
          "short": "CHE",
          "fullName": "Chemistry",
          "seat": 90,
          "reviewLink": "https://study.mnr.world/CHE/"
        },
        {
          "short": "CSE",
          "fullName": "Computer Science and Engineering",
          "seat": 65,
          "reviewLink": "https://study.mnr.world/CSE/"
        },
        {
          "short": "DSC",
          "fullName": "Disaster Science and Climate Resilience",
          "seat": 30,
          "reviewLink": "https://study.mnr.world/DSC/"
        },
        {
          "short": "EEE",
          "fullName": "Electrical and Electronic Engineering",
          "seat": 75,
          "reviewLink": "https://study.mnr.world/EEE/"
        },
        {
          "short": "FE",
          "fullName": "Footwear Engineering",
          "seat": 50,
          "reviewLink": "https://study.mnr.world/FE/"
        },
        {
          "short": "FIS",
          "fullName": "Fisheries",
          "seat": 40,
          "reviewLink": "https://study.mnr.world/FIS/"
        },
        {
          "short": "GEB",
          "fullName": "Genetic Engineering and Biotechnology",
          "seat": 30,
          "reviewLink": "https://study.mnr.world/GEB/"
        },
        {
          "short": "GEO",
          "fullName": "Geography and Environment",
          "seat": 80,
          "tooltip": "<b>Science:</b> 50<br><b>Arts:</b> 25<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/GEO/"
        },
        {
          "short": "GLY",
          "fullName": "Geology",
          "seat": 50,
          "reviewLink": "https://study.mnr.world/GLY/"
        },
        {
          "short": "LE",
          "fullName": "Leather Engineering",
          "seat": 50,
          "reviewLink": "https://study.mnr.world/LE/"
        },
        {
          "short": "LPE",
          "fullName": "Leather Products Engineering",
          "seat": 50,
          "reviewLink": "https://study.mnr.world/LPE/"
        },
        {
          "short": "MAT",
          "fullName": "Mathematics",
          "seat": 130,
          "tooltip": "<b>Science:</b> 127<br><b>Arts:</b> 3",
          "reviewLink": "https://study.mnr.world/MAT/"
        },
        {
          "short": "MET",
          "fullName": "Meteorology",
          "seat": 30,
          "reviewLink": "https://study.mnr.world/MET/"
        },
        {
          "short": "MIC",
          "fullName": "Microbiology",
          "seat": 40,
          "reviewLink": "https://study.mnr.world/MIC/"
        },
        {
          "short": "NE",
          "fullName": "Nuclear Engineering",
          "seat": 30,
          "reviewLink": "https://study.mnr.world/NE/"
        },
        {
          "short": "NFS",
          "fullName": "Nutrition and Food Science",
          "seat": 40,
          "reviewLink": "https://study.mnr.world/NFS/"
        },
        {
          "short": "OCN",
          "fullName": "Oceanography",
          "seat": 40,
          "reviewLink": "https://study.mnr.world/OCN/"
        },
        {
          "short": "PHA",
          "fullName": "Pharmacy",
          "seat": 85,
          "reviewLink": "https://study.mnr.world/PHA/"
        },
        {
          "short": "PHY",
          "fullName": "Physics",
          "seat": 100,
          "reviewLink": "https://study.mnr.world/PHY/"
        },
        {
          "short": "PS",
          "fullName": "Physical Science",
          "seat": 22,
          "reviewLink": "https://study.mnr.world/PS/"
        },
        {
          "short": "PSY",
          "fullName": "Psychology",
          "seat": 80,
          "tooltip": "<b>Science:</b> 40<br><b>Arts:</b> 20<br><b>Commerce:</b> 20",
          "reviewLink": "https://study.mnr.world/PSY/"
        },
        {
          "short": "RME",
          "fullName": "Robotics and Mechanics Engineering",
          "seat": 30,
          "reviewLink": "https://study.mnr.world/RME/"
        },
        {
          "short": "SE",
          "fullName": "Software Engineering",
          "seat": 55,
          "reviewLink": "https://study.mnr.world/SE/"
        },
        {
          "short": "STA",
          "fullName": "Statistics",
          "seat": 90,
          "tooltip": "<b>Science:</b> 87<br><b>Arts:</b> 3",
          "reviewLink": "https://study.mnr.world/STA/"
        },
        {
          "short": "SWE",
          "fullName": "Soil, Water & Environment",
          "seat": 100,
          "reviewLink": "https://study.mnr.world/SWE/"
        },
        {
          "short": "ZOO",
          "fullName": "Zoology",
          "seat": 80,
          "reviewLink": "https://study.mnr.world/ZOO/"
        }
      ],
      "unitB": [
        {
          "short": "B",
          "fullName": "Bangla",
          "seat": 110,
          "tooltip": "<b>Arts:</b> 80<br><b>Science:</b> 25<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/B/"
        },
        {
          "short": "E",
          "fullName": "English",
          "seat": 110,
          "tooltip": "<b>Arts:</b> 90<br><b>Science:</b> 15<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/E/"
        },
        {
          "short": "A",
          "fullName": "Arabic",
          "seat": 100,
          "tooltip": "<b>Arts:</b> 80<br><b>Science:</b> 20",
          "reviewLink": "https://study.mnr.world/A/"
        },
        {
          "short": "PLL",
          "fullName": "Persian Language and Literature",
          "seat": 75,
          "tooltip": "<b>Arts:</b> 60<br><b>Science:</b> 10<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/PLL/"
        },
        {
          "short": "U",
          "fullName": "Urdu",
          "seat": 70,
          "tooltip": "<b>Arts:</b> 60<br><b>Science:</b> 5<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/U/"
        },
        {
          "short": "S",
          "fullName": "Sanskrit",
          "seat": 75,
          "tooltip": "<b>Arts:</b> 55<br><b>Science:</b> 15<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/S/"
        },
        {
          "short": "PBS",
          "fullName": "Pali and Buddhist Studies",
          "seat": 50,
          "tooltip": "<b>Arts:</b> 35<br><b>Science:</b> 10<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/PBS/"
        },
        {
          "short": "H",
          "fullName": "History",
          "seat": 110,
          "tooltip": "<b>Arts:</b> 85<br><b>Science:</b> 18<br><b>Commerce:</b> 7",
          "reviewLink": "https://study.mnr.world/H/"
        },
        {
          "short": "PHI",
          "fullName": "Philosophy",
          "seat": 120,
          "tooltip": "<b>Arts:</b> 96<br><b>Science:</b> 18<br><b>Commerce:</b> 6",
          "reviewLink": "https://study.mnr.world/PHI/"
        },
        {
          "short": "IS",
          "fullName": "Islamic Studies",
          "seat": 100,
          "tooltip": "<b>Arts:</b> 95<br><b>Science:</b> 5",
          "reviewLink": "https://study.mnr.world/IS/"
        },
        {
          "short": "IHAC",
          "fullName": "Islamic History and Culture",
          "seat": 110,
          "tooltip": "<b>Arts:</b> 90<br><b>Science:</b> 12<br><b>Commerce:</b> 8",
          "reviewLink": "https://study.mnr.world/IHAC/"
        },
        {
          "short": "ITLM",
          "fullName": "Information technology and Library management",
          "seat": 65,
          "tooltip": "<b>Arts:</b> 45<br><b>Science:</b> 15<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/ITLM/"
        },
        {
          "short": "TPS",
          "fullName": "Theatre and Performance Studies",
          "seat": 25,
          "tooltip": "<b>Arts:</b> 13<br><b>Science:</b> 8<br><b>Commerce:</b> 4",
          "reviewLink": "https://study.mnr.world/TPS/"
        },
        {
          "short": "L",
          "fullName": "Linguistics",
          "seat": 70,
          "tooltip": "<b>Arts:</b> 45<br><b>Science:</b> 20<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/L/"
        },
        {
          "short": "M",
          "fullName": "Music",
          "seat": 60,
          "tooltip": "<b>Arts:</b> 30<br><b>Science:</b> 20<br><b>Commerce:</b> 10",
          "reviewLink": "https://study.mnr.world/M/"
        },
        {
          "short": "WRC",
          "fullName": "World Religion and Culture",
          "seat": 60,
          "tooltip": "<b>Arts:</b> 40<br><b>Science:</b> 15<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/WRC/"
        },
        {
          "short": "D",
          "fullName": "Dance",
          "seat": 30,
          "tooltip": "<b>Arts:</b> 20<br><b>Science:</b> 5<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/D/"
        },
        {
          "short": "ECON",
          "fullName": "Economics",
          "seat": 130,
          "tooltip": "<b>Arts:</b> 50<br><b>Science:</b> 72<br><b>Commerce:</b> 8",
          "reviewLink": "https://study.mnr.world/ECON/"
        },
        {
          "short": "PS",
          "fullName": "Political Science",
          "seat": 150,
          "tooltip": "<b>Arts:</b> 75<br><b>Science:</b> 60<br><b>Commerce:</b> 15",
          "reviewLink": "https://study.mnr.world/PS/"
        },
        {
          "short": "IR",
          "fullName": "International Relation",
          "seat": 80,
          "tooltip": "<b>Arts:</b> 40<br><b>Science:</b> 35<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/IR/"
        },
        {
          "short": "SO",
          "fullName": "Sociology",
          "seat": 150,
          "tooltip": "<b>Arts:</b> 75<br><b>Science:</b> 65<br><b>Commerce:</b> 10",
          "reviewLink": "https://study.mnr.world/SO/"
        },
        {
          "short": "MCJ",
          "fullName": "Mass Communication and Journalism",
          "seat": 65,
          "tooltip": "<b>Arts:</b> 32<br><b>Science:</b> 25<br><b>Commerce:</b> 8",
          "reviewLink": "https://study.mnr.world/MCJ/"
        },
        {
          "short": "PA",
          "fullName": "Public Administration",
          "seat": 90,
          "tooltip": "<b>Arts:</b> 30<br><b>Science:</b> 30<br><b>Commerce:</b> 30",
          "reviewLink": "https://study.mnr.world/PA/"
        },
        {
          "short": "ANT",
          "fullName": "Anthropology",
          "seat": 55,
          "tooltip": "<b>Arts:</b> 25<br><b>Science:</b> 25<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/ANT/"
        },
        {
          "short": "POP",
          "fullName": "Population Science",
          "seat": 40,
          "tooltip": "<b>Arts:</b> 14<br><b>Science:</b> 26",
          "reviewLink": "https://study.mnr.world/POP/"
        },
        {
          "short": "PCS",
          "fullName": "Peace and Conflict Studies",
          "seat": 40,
          "tooltip": "<b>Arts:</b> 20<br><b>Science:</b> 15<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/PCS/"
        },
        {
          "short": "WGS",
          "fullName": "Women and Gender Studies",
          "seat": 40,
          "tooltip": "<b>Arts:</b> 17<br><b>Science:</b> 20<br><b>Commerce:</b> 3",
          "reviewLink": "https://study.mnr.world/WGS/"
        },
        {
          "short": "DS",
          "fullName": "Development Studies",
          "seat": 40,
          "tooltip": "<b>Arts:</b> 15<br><b>Science:</b> 19<br><b>Commerce:</b> 6",
          "reviewLink": "https://study.mnr.world/DS/"
        },
        {
          "short": "TFP",
          "fullName": "Television, Film, and Photography",
          "seat": 30,
          "tooltip": "<b>Arts:</b> 5<br><b>Science:</b> 15<br><b>Commerce:</b> 10",
          "reviewLink": "https://study.mnr.world/TFP/"
        },
        {
          "short": "CRIM",
          "fullName": "Criminology",
          "seat": 50,
          "tooltip": "<b>Arts:</b> 10<br><b>Science:</b> 35<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/CRIM/"
        },
        {
          "short": "CD",
          "fullName": "Communication Disorders",
          "seat": 30,
          "tooltip": "<b>Arts:</b> 10<br><b>Science:</b> 20",
          "reviewLink": "https://study.mnr.world/CD/"
        },
        {
          "short": "PPS",
          "fullName": "Print and Publication Studies",
          "seat": 30,
          "tooltip": "<b>Arts:</b> 10<br><b>Science:</b> 15<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/PPS/"
        },
        {
          "short": "JS",
          "fullName": "Japanese Studies",
          "seat": 50,
          "tooltip": "<b>Arts:</b> 10<br><b>Science:</b> 30<br><b>Commerce:</b> 10",
          "reviewLink": "https://study.mnr.world/JS/"
        },
        {
          "short": "LAW",
          "fullName": "Law",
          "seat": 110,
          "tooltip": "<b>Arts:</b> 55<br><b>Science:</b> 37<br><b>Commerce:</b> 18",
          "reviewLink": "https://study.mnr.world/LAW/"
        },
        {
          "short": "SSW",
          "fullName": "Social Welfare and Research Institute",
          "seat": 100,
          "tooltip": "<b>Arts:</b> 85<br><b>Science:</b> 12<br><b>Commerce:</b> 3",
          "reviewLink": "https://study.mnr.world/SSW/"
        },
        {
          "short": "HEI",
          "fullName": "Health Economics Institute",
          "seat": 60,
          "tooltip": "<b>Arts:</b> 30<br><b>Science:</b> 30",
          "reviewLink": "https://study.mnr.world/HEI/"
        },
        {
          "short": "IDMVS",
          "fullName": "Institute of Disaster Management and Vulnerability Studies",
          "seat": 45,
          "tooltip": "<b>Arts:</b> 10<br><b>Science:</b> 25<br><b>Commerce:</b> 10",
          "reviewLink": "https://study.mnr.world/IDMVS/"
        },
        {
          "short": "LED",
          "fullName": "Language Education Department",
          "seat": 26,
          "tooltip": "<b>Arts:</b> 6<br><b>Science:</b> 16<br><b>Commerce:</b> 4",
          "reviewLink": "https://study.mnr.world/LED/"
        },
        {
          "short": "SSED",
          "fullName": "Social Science Education Department",
          "seat": 30,
          "tooltip": "<b>Arts:</b> 8<br><b>Science:</b> 15<br><b>Commerce:</b> 7",
          "reviewLink": "https://study.mnr.world/SSED/"
        },
        {
          "short": "SED",
          "fullName": "Special Education Department",
          "seat": 23,
          "tooltip": "<b>Arts:</b> 3<br><b>Science:</b> 20",
          "reviewLink": "https://study.mnr.world/SED/"
        },
        {
          "short": "ESOL",
          "fullName": "English for Speakers of Other Languages (ESOL)",
          "seat": 40,
          "tooltip": "<b>Arts:</b> 23<br><b>Science:</b> 11<br><b>Commerce:</b> 6",
          "reviewLink": "https://study.mnr.world/ESOL/"
        },
        {
          "short": "FLC",
          "fullName": "French Language and Culture (FLC)",
          "seat": 30,
          "tooltip": "<b>Arts:</b> 10<br><b>Science:</b> 10<br><b>Commerce:</b> 10",
          "reviewLink": "https://study.mnr.world/FLC/"
        },
        {
          "short": "CLC",
          "fullName": "Chinese Language and Culture (CLC)",
          "seat": 30,
          "tooltip": "<b>Arts:</b> 10<br><b>Science:</b> 15<br><b>Commerce:</b> 5",
          "reviewLink": "https://study.mnr.world/CLC/"
        },
        {
          "short": "JLC",
          "fullName": "Japanese Language and Culture (JLC)",
          "seat": 30,
          "tooltip": "<b>Arts:</b> 10<br><b>Science:</b> 10<br><b>Commerce:</b> 10",
          "reviewLink": "https://study.mnr.world/JLC/"
        }
      ],
      "unitC": [
        {
          "short": "MGMT",
          "fullName": "Management",
          "seat": 150,
          "tooltip": "<b>Commerce:</b> 135<br><b>Science:</b> 12<br><b>Arts:</b> 3",
          "reviewLink": "https://study.mnr.world/MGMT/"
        },
        {
          "short": "AIS",
          "fullName": "Accounting and Information System",
          "seat": 150,
          "tooltip": "<b>Commerce:</b> 135<br><b>Science:</b> 12<br><b>Arts:</b> 3",
          "reviewLink": "https://study.mnr.world/AIS/"
        },
        {
          "short": "MKT",
          "fullName": "Marketing",
          "seat": 150,
          "tooltip": "<b>Commerce:</b> 135<br><b>Science:</b> 12<br><b>Arts:</b> 3",
          "reviewLink": "https://study.mnr.world/MKT/"
        },
        {
          "short": "FIN",
          "fullName": "Finance",
          "seat": 150,
          "tooltip": "<b>Commerce:</b> 135<br><b>Science:</b> 12<br><b>Arts:</b> 3",
          "reviewLink": "https://study.mnr.world/FIN/"
        },
        {
          "short": "BI",
          "fullName": "Banking and Insurance",
          "seat": 100,
          "tooltip": "<b>Commerce:</b> 90<br><b>Science:</b> 8<br><b>Arts:</b> 2",
          "reviewLink": "https://study.mnr.world/BI/"
        },
        {
          "short": "MIS",
          "fullName": "Management and Information System",
          "seat": 100,
          "tooltip": "<b>Commerce:</b> 90<br><b>Science:</b> 8<br><b>Arts:</b> 2",
          "reviewLink": "https://study.mnr.world/MIS/"
        },
        {
          "short": "THM",
          "fullName": "Tourism and Hospitality Management",
          "seat": 100,
          "tooltip": "<b>Commerce:</b> 90<br><b>Science:</b> 8<br><b>Arts:</b> 2",
          "reviewLink": "https://study.mnr.world/THM/"
        },
        {
          "short": "IB",
          "fullName": "International Business",
          "seat": 100,
          "tooltip": "<b>Commerce:</b> 90<br><b>Science:</b> 8<br><b>Arts:</b> 2",
          "reviewLink": "https://study.mnr.world/IB/"
        },
        {
          "short": "OSL",
          "fullName": "Organization Strategy and Leadership",
          "seat": 50,
          "tooltip": "<b>Commerce:</b> 30<br><b>Science:</b> 15<br><b>Arts:</b> 5",
          "reviewLink": "https://study.mnr.world/OSL/"
        }
      ],
      "unitCha": [
        {
          "short": "অঙ্কন ও চিত্রায়ণ",
          "fullName": "অঙ্কন ও চিত্রায়ণ",
          "seat": 25,
          "reviewLink": "#"
        },
        {
          "short": "গ্রাফিক ডিজাইন",
          "fullName": "গ্রাফিক ডিজাইন",
          "seat": 25,
          "reviewLink": "#"
        },
        {
          "short": "প্রিন্টমেকিং",
          "fullName": "প্রিন্টমেকিং",
          "seat": 12,
          "reviewLink": "#"
        },
        {
          "short": "প্রাচ্যকলা",
          "fullName": "প্রাচ্যকলা",
          "seat": 15,
          "reviewLink": "#"
        },
        {
          "short": "মৃৎশিল্প",
          "fullName": "মৃৎশিল্প",
          "seat": 10,
          "reviewLink": "#"
        },
        {
          "short": "ভাস্কর্য",
          "fullName": "ভাস্কর্য",
          "seat": 10,
          "reviewLink": "#"
        },
        {
          "short": "কারুশিল্প",
          "fullName": "কারুশিল্প",
          "seat": 15,
          "reviewLink": "#"
        },
        {
          "short": "শিল্পকলার ইতিহাস",
          "fullName": "শিল্পকলার ইতিহাস",
          "seat": 18,
          "reviewLink": "#"
        }
      ],
      "unitIBA": [
        {
          "short": "IBA",
          "fullName": "Institute of Business Administration",
          "seat": 120,
          "reviewLink": "https://study.mnr.world/IBA/"
        }
      ]
    }
  },
  {
    "nameBn": "রাজশাহী বিশ্ববিদ্যালয়",
    "nameEn": "University of Rajshahi",
    "shortName": "RU",
    "id": "ru",
    "category": [
      "সাধারণ"
    ],
    "description": "দেশের দ্বিতীয় বৃহত্তম বিশ্ববিদ্যালয়, যা শিক্ষানগরী রাজশাহীতে অবস্থিত।",
    "link": "/ru",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/RU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "চট্টগ্রাম বিশ্ববিদ্যালয়",
    "nameEn": "University of Chittagong",
    "shortName": "CU",
    "id": "cu",
    "category": [
      "সাধারণ"
    ],
    "description": "প্রাকৃতিক সৌন্দর্যে ঘেরা দেশের অন্যতম বৃহৎ একটি বিশ্ববিদ্যালয়।",
    "link": "/cu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/CU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "জাহাঙ্গীরনগর বিশ্ববিদ্যালয়",
    "nameEn": "Jahangirnagar University",
    "shortName": "JU",
    "id": "ju",
    "category": [
      "সাধারণ"
    ],
    "description": "বাংলাদেশের একমাত্র আবাসিক পাবলিক বিশ্ববিদ্যালয়।",
    "link": "/ju",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/JU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "GST গুচ্ছ",
    "nameEn": "GST Guccho",
    "shortName": "GST",
    "id": "gst",
    "category": [
      "গুচ্ছ"
    ],
    "description": "GST গুচ্ছভুক্ত বিশ্ববিদ্যালয় মোট ১৯টি (সাধারণ+বিজ্ঞান ও প্রযুক্তি)",
    "link": "/gst",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/GST.png"
  },
  {
    "nameBn": "কৃষি গুচ্ছ",
    "nameEn": "Cluster Agri",
    "shortName": "ACAS",
    "id": "agri",
    "category": [
      "গুচ্ছ"
    ],
    "description": "কৃষি গুচ্ছভুক্ত বিশ্ববিদ্যালয় মোট ৮টি (সাধারণ+ভেটেরিনারি)",
    "link": "/agri",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/Agri.png"
  },
  {
    "nameBn": "মেডিকেল গুচ্ছ",
    "nameEn": "Medical Guccho",
    "shortName": "Medical",
    "id": "Medical",
    "category": [
      "মেডিকেল",
      "গুচ্ছ"
    ],
    "description": "বাংলাদেশে সরকারি মেডিকেল কলেজ প্রায় ৩৭টি",
    "link": "/Medical",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/Medical.png"
  },
  {
    "nameBn": "ডেন্টাল গুচ্ছ",
    "nameEn": "Dental Guccho",
    "shortName": "Dental",
    "id": "Dental",
    "category": [
      "মেডিকেল",
      "গুচ্ছ"
    ],
    "description": "বাংলাদেশে সরকারি ডেন্টাল কলেজ ও ডেন্টাল ইউনিট প্রায় ৮টি",
    "link": "/Dental",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/Dental.png"
  },
  {
    "nameBn": "আর্মড ফোর্সেস মেডিকেল কলেজ",
    "nameEn": "Armed Forces Medical College",
    "shortName": "AFMC",
    "id": "afmc",
    "category": [
      "মেডিকেল"
    ],
    "description": "আর্মড ফোর্সেস মেডিক্যাল কলেজ (এএফএমসি) ঢাকা ক্যান্টনমেন্টের অভ্যন্তরে অবস্থিত একটি সরকারি মেডিকেল কলেজ",
    "link": "/afmc",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/AFMC.png"
  },
  {
    "nameBn": "নার্সিং গুচ্ছ",
    "nameEn": "Nursing Guccho",
    "shortName": "Nursing",
    "id": "Nursing",
    "category": [
      "মেডিকেল",
      "গুচ্ছ"
    ],
    "description": "বাংলাদেশ সরকারি নার্সিং ও মিডওয়াইফারি শিক্ষাপ্রতিষ্ঠানসমূহ প্রায় ২৭টি",
    "link": "/Nursing",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/Nursing.png"
  },
  {
    "nameBn": "নিটোর",
    "nameEn": "NITOR",
    "shortName": "NITOR",
    "id": "NITOR",
    "category": [
      "মেডিকেল"
    ],
    "description": "National Institute Of Traumatology And Orthopaedic Rehabilitation (NITOR)-কে পুরো বাংলাদেশের মানুষ বাংলাদেশ পঙ্গু হাসপাতাল নামে চিনে থাকে",
    "link": "/NITOR",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/NITOR.png"
  },
  {
    "nameBn": "বাংলাদেশ কৃষি বিশ্ববিদ্যালয়",
    "nameEn": "Bangladesh Agricultural University",
    "shortName": "BAU",
    "id": "bau",
    "category": [
      "কৃষি"
    ],
    "description": "কৃষি বিষয়ক উচ্চশিক্ষার অন্যতম সেরা একটি প্রতিষ্ঠান।",
    "link": "/bau",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/BAU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "চট্টগ্রাম ভেটেরিনারি ও এনিম্যাল সাইন্সেস বিশ্ববিদ্যালয়",
    "nameEn": "Chittagong Veterinary and Animal Sciences University",
    "shortName": "CVASU",
    "id": "cvasu",
    "category": [
      "কৃষি"
    ],
    "description": "প্রাণী ও মৎস্য বিজ্ঞানের জন্য বিশেষায়িত একটি বিশ্ববিদ্যালয়।",
    "link": "/cvasu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/CVASU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "বঙ্গবন্ধু শেখ মুজিবুর রহমান কৃষি বিশ্ববিদ্যালয়",
    "nameEn": "Bangabandhu Sheikh Mujibur Rahman Agricultural University",
    "shortName": "BSMRAU",
    "id": "gau",
    "category": [
      "কৃষি"
    ],
    "description": "গাজীপুরে অবস্থিত একটি আন্তর্জাতিক মানের কৃষি শিক্ষা ও গবেষণা প্রতিষ্ঠান।",
    "link": "/bsmrau",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/GAU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "হবিগঞ্জ কৃষি বিশ্ববিদ্যালয়",
    "nameEn": "Habiganj Agricultural University",
    "shortName": "HAU",
    "id": "hau",
    "category": [
      "কৃষি"
    ],
    "description": "হাওর অঞ্চলের কৃষি উন্নয়নে প্রতিষ্ঠিত একটি নতুন বিশ্ববিদ্যালয়।",
    "link": "/hau",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/HAU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "খুলনা কৃষি বিশ্ববিদ্যালয়",
    "nameEn": "Khulna Agricultural University",
    "shortName": "KAU",
    "id": "kau",
    "category": [
      "কৃষি"
    ],
    "description": "দক্ষিণ-পশ্চিমাঞ্চলের কৃষি গবেষণার জন্য একটি গুরুত্বপূর্ণ প্রতিষ্ঠান।",
    "link": "/kau",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/KAU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "কুড়িগ্রাম কৃষি বিশ্ববিদ্যালয়",
    "nameEn": "Kurigram Agricultural University",
    "shortName": "KuriAU",
    "id": "kuriau",
    "category": [
      "কৃষি"
    ],
    "description": "উত্তরবঙ্গের কৃষি উন্নয়নে প্রতিষ্ঠিত একটি নতুন পাবলিক বিশ্ববিদ্যালয়।",
    "link": "/kuriau",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/KuriAU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "সিলেট কৃষি বিশ্ববিদ্যালয়",
    "nameEn": "Sylhet Agricultural University",
    "shortName": "SAU",
    "id": "sau",
    "category": [
      "কৃষি"
    ],
    "description": "সিলেট বিভাগে অবস্থিত কৃষি ও প্রাণী বিজ্ঞানের একটি বিশেষায়িত বিশ্ববিদ্যালয়।",
    "link": "/sau",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/SAU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "শেরেবাংলা কৃষি বিশ্ববিদ্যালয়",
    "nameEn": "Sher-e-Bangla Agricultural University",
    "shortName": "SBAU",
    "id": "sbau",
    "category": [
      "কৃষি"
    ],
    "description": "ঢাকার শেরেবাংলা নগره অবস্থিত একটি ঐতিহ্যবাহী কৃষি শিক্ষা প্রতিষ্ঠান।",
    "link": "/sbau",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/SBAU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "বাংলাদেশ প্রকৌশল বিশ্ববিদ্যালয়",
    "nameEn": "Bangladesh University of Engineering and Technology",
    "shortName": "BUET",
    "id": "buet",
    "category": [
      "প্রকৌশল"
    ],
    "description": "দেশের শীর্ষস্থানীয় প্রকৌশল শিক্ষা প্রতিষ্ঠান।",
    "link": "/buet",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/BUET.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "খুলনা প্রকৌশল ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Khulna University of Engineering & Technology",
    "shortName": "KUET",
    "id": "kuet",
    "category": [
      "প্রকৌশল"
    ],
    "description": "দক্ষিণবঙ্গের অন্যতম সেরা প্রকৌশল বিশ্ববিদ্যালয়।",
    "link": "/kuet",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/KUET.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "রাজশাহী প্রকৌশল ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Rajshahi University of Engineering & Technology",
    "shortName": "RUET",
    "id": "ruet",
    "category": [
      "প্রকৌশল"
    ],
    "description": "উত্তরবঙ্গের শিক্ষার্থীদের জন্য প্রকৌশল শিক্ষার বাতিঘর।",
    "link": "/ruet",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/RUET.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "চট্টগ্রাম প্রকৌশল ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Chittagong University of Engineering & Technology",
    "shortName": "CUET",
    "id": "cuet",
    "category": [
      "প্রকৌশল"
    ],
    "description": "চট্টগ্রামের প্রধান প্রকৌশল শিক্ষা ও গবেষণা প্রতিষ্ঠান।",
    "link": "/cuet",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/CUET.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "ঢাকা প্রকৌশল ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Dhaka University of Engineering & Technology",
    "shortName": "DUET",
    "id": "duet",
    "category": [
      "প্রকৌশল"
    ],
    "description": "ডিপ্লোমা ইন ইঞ্জিনিয়ারিং সম্পন্নকারীদের জন্য বিশেষায়িত বিশ্ববিদ্যালয়।",
    "link": "/duet",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/DUET.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "সামরিক বিজ্ঞান ও প্রযুক্তি ইনস্টিটিউট",
    "nameEn": "Military Institute of Science and Technology",
    "shortName": "MIST",
    "id": "mist",
    "category": [
      "প্রকৌশল"
    ],
    "description": "বাংলাদেশ সশস্ত্র বাহিনী দ্বারা পরিচালিত একটি উন্নত প্রযুক্তিগত শিক্ষা প্রতিষ্ঠান।",
    "link": "/mist",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/MIST.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "শাহজালাল বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Shahjalal University of Science and Technology",
    "shortName": "SUST",
    "id": "sust",
    "category": [
      "বিজ্ঞান ও প্রযুক্তি"
    ],
    "description": "বিজ্ঞান ও প্রযুক্তি গবেষণায় দেশের অন্যতম সেরা একটি বিশ্ববিদ্যালয়।",
    "link": "/sust",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/SUST.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "যশোর বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Jashore University of Science and Technology",
    "shortName": "JUST",
    "id": "just",
    "category": [
      "বিজ্ঞান ও প্রযুক্তি"
    ],
    "description": "দেশের দক্ষিণ-পশ্চিমাঞ্চলের একটি অন্যতম বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়।",
    "link": "/just",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/JUST.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "মাওলানা ভাসানী বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Mawlana Bhashani Science and Technology University",
    "shortName": "MBSTU",
    "id": "mbstu",
    "category": [
      "বিজ্ঞান ও প্রযুক্তি"
    ],
    "description": "টাঙ্গাইলে অবস্থিত একটি সরকারি বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়।",
    "link": "/mbstu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/MBSTU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "হাজী মোহাম্মদ দানেশ বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Hajee Mohammad Danesh Science & Technology University",
    "shortName": "HSTU",
    "id": "hstu",
    "category": [
      "বিজ্ঞান ও প্রযুক্তি"
    ],
    "description": "উত্তরবঙ্গের একটি শীর্ষস্থানীয় বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়।",
    "link": "/hstu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/HSTU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "নোয়াখালী বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Noakhali Science and Technology University",
    "shortName": "NSTU",
    "id": "nstu",
    "category": [
      "বিজ্ঞান ও প্রযুক্তি"
    ],
    "description": "নোয়াখালী জেলায় অবস্থিত একটি সরকারি বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়।",
    "link": "/nstu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/NSTU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "পটুয়াখালী বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Patuakhali Science and Technology University",
    "shortName": "PSTU",
    "id": "pstu",
    "category": [
      "বিজ্ঞান ও প্রযুক্তি"
    ],
    "description": "বরিশাল বিভাগে অবস্থিত একটি বিশেষায়িত সরকারি বিশ্ববিদ্যালয়।",
    "link": "/pstu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/PSTU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "পাবনা বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Pabna University of Science and Technology",
    "shortName": "PUST",
    "id": "pust",
    "category": [
      "বিজ্ঞান ও প্রযুক্তি"
    ],
    "description": "পাবনা জেলায় অবস্থিত একটি পাবলিক বিশ্ববিদ্যালয়।",
    "link": "/pust",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/PUST.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "রাঙ্গামাটি বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Rangamati Science and Technology University",
    "shortName": "RMSTU",
    "id": "rmstu",
    "category": [
      "বিজ্ঞান ও প্রযুক্তি"
    ],
    "description": "পার্বত্য চট্টগ্রাম অঞ্চলের প্রথম পাবলিক বিশ্ববিদ্যালয়।",
    "link": "/rmstu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/RMSTU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "বগুড়া বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Bogura Science and Technology University",
    "shortName": "BSTU",
    "id": "bstu",
    "category": [
      "বিজ্ঞান ও প্রযুক্তি"
    ],
    "description": "বগুড়া জেলায় অবস্থিত একটি নতুন পাবলিক বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়।",
    "link": "/bstu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/BSTU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "চাঁদপুর বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Chandpur Science and Technology University",
    "shortName": "CSTU",
    "id": "cstu",
    "category": [
      "বিজ্ঞান ও প্রযুক্তি"
    ],
    "description": "চাঁদপুর জেলায় অবস্থিত একটি নতুন পাবলিক বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়।",
    "link": "/cstu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/CSTU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "বঙ্গবন্ধু শেখ মুজিবুর রহমান বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়, গোপালগঞ্জ",
    "nameEn": "Bangabandhu Sheikh Mujibur Rahman Science and Technology University, Gopalganj",
    "shortName": "BSMRSTU",
    "id": "gstu",
    "category": [
      "বিজ্ঞান ও প্রযুক্তি"
    ],
    "description": "গোপালগঞ্জ জেলায় অবস্থিত একটি সরকারি বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়।",
    "link": "/gstu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/GSTU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "জামালপুর বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Jamalpur Science and Technology University",
    "shortName": "JSTU",
    "id": "jstu",
    "category": [
      "বিজ্ঞান ও প্রযুক্তি"
    ],
    "description": "জামালপুর জেলায় অবস্থিত একটি নতুন পাবলিক বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়।",
    "link": "/jstu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/JSTU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "পিরোজপুর বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Pirojpur Science and Technology University",
    "shortName": "PrSTU",
    "id": "prstu",
    "category": [
      "বিজ্ঞান ও প্রযুক্তি"
    ],
    "description": "পিরোজপুর জেলায় অবস্থিত একটি নতুন পাবলিক বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়।",
    "link": "/prstu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/PrSTU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "সুনামগঞ্জ বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Sunamganj Science and Technology University",
    "shortName": "SSTU",
    "id": "sstu",
    "category": [
      "বিজ্ঞান ও প্রযুক্তি"
    ],
    "description": "সুনামগঞ্জ জেলায় অবস্থিত একটি নতুন পাবলিক বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়।",
    "link": "/sstu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/SSTU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "ইসলামী বিশ্ববিদ্যালয়",
    "nameEn": "Islamic University, Bangladesh",
    "shortName": "IU",
    "id": "iu",
    "category": [
      "সাধারণ"
    ],
    "description": "ধর্মতত্ত্ব ও আধুনিক শিক্ষার সমন্বয়ে গঠিত একটি বিশ্ববিদ্যালয়।",
    "link": "/iu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/IU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "খুলনা বিশ্ববিদ্যালয়",
    "nameEn": "Khulna University",
    "shortName": "KU",
    "id": "ku",
    "category": [
      "সাধারণ"
    ],
    "description": "সেশনজট মুক্ত একটি পাবলিক বিশ্ববিদ্যালয়।",
    "link": "/ku",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/KU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "জগন্নাথ বিশ্ববিদ্যালয়",
    "nameEn": "Jagannath University",
    "shortName": "JnU",
    "id": "jnu",
    "category": [
      "সাধারণ"
    ],
    "description": "ঢাকার প্রাণকেন্দ্রে অবস্থিত একটি ঐতিহ্যবাহী শিক্ষা প্রতিষ্ঠান।",
    "link": "/jnu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/JnU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "কুমিল্লা বিশ্ববিদ্যালয়",
    "nameEn": "Comilla University",
    "shortName": "CoU",
    "id": "cou",
    "category": [
      "সাধারণ"
    ],
    "description": "ময়নামতির কোলে অবস্থিত একটি দ্রুত বর্ধনশীল বিশ্ববিদ্যালয়।",
    "link": "/cou",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/CoU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "জাতীয় কবি কাজী নজরুল ইসলাম বিশ্ববিদ্যালয়",
    "nameEn": "Jatiya Kabi Kazi Nazrul Islam University",
    "shortName": "JKKNIU",
    "id": "jkkniu",
    "category": [
      "সাধারণ"
    ],
    "description": "সাহিত্য ও সংস্কৃতি চর্চার জন্য পরিচিত একটি বিশ্ববিদ্যালয়।",
    "link": "/jkkniu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/JKKNIU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "বেগম রোকেয়া বিশ্ববিদ্যালয়, রংপুর",
    "nameEn": "Begum Rokeya University, Rangpur",
    "shortName": "BRUR",
    "id": "brur",
    "category": [
      "সাধারণ"
    ],
    "description": "উত্তরবঙ্গের নারী জাগরণের অগ্রদূতের নামে প্রতিষ্ঠিত একটি বিশ্ববিদ্যালয়।",
    "link": "/brur",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/BRUR.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "বরিশাল বিশ্ববিদ্যালয়",
    "nameEn": "University of Barisal",
    "shortName": "BU",
    "id": "bu",
    "category": [
      "সাধারণ"
    ],
    "description": "কীর্তনখোলা নদীর তীরে অবস্থিত বরিশাল বিভাগের একমাত্র পাবলিক বিশ্ববিদ্যালয়।",
    "link": "/bu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/BU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "কিশোরগঞ্জ বিশ্ববিদ্যালয়",
    "nameEn": "Kishoreganj University",
    "shortName": "KiU",
    "id": "kiu",
    "category": [
      "সাধারণ"
    ],
    "description": "কিশোরগঞ্জ জেলায় অবস্থিত একটি নতুন পাবলিক বিশ্ববিদ্যালয়।",
    "link": "/kiu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/KiU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "নেত্রকোনা বিশ্ববিদ্যালয়",
    "nameEn": "Netrokona University",
    "shortName": "NeU",
    "id": "neu",
    "category": [
      "সাধারণ"
    ],
    "description": "নেত্রকোনা জেলায় অবস্থিত একটি নতুন পাবলিক বিশ্ববিদ্যালয়।",
    "link": "/neu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/NeU.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "রবীন্দ্র বিশ্ববিদ্যালয়, বাংলাদেশ",
    "nameEn": "Rabindra University, Bangladesh",
    "shortName": "RUB",
    "id": "rub",
    "category": [
      "সাধারণ"
    ],
    "description": "বিশ্বকবি রবীন্দ্রনাথ ঠাকুরের নামে প্রতিষ্ঠিত একটি সাংস্কৃতিক ও সাধারণ বিশ্ববিদ্যালয়।",
    "link": "/rub",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/RUB.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "বঙ্গবন্ধু শেখ মুজিবুর রহমান অ্যাভিয়েশন অ্যান্ড অ্যারোস্পেস বিশ্ববিদ্যালয়",
    "nameEn": "Bangabandhu Sheikh Mujibur Rahman Aviation and Aerospace University",
    "shortName": "BSMRAAU",
    "id": "aaub",
    "category": [
      "বিশেষ",
      "প্রকৌশল"
    ],
    "description": "এটি বাংলাদেশের একটি সরকারি, স্বনামধন্য এবং মহাকাশ প্রকৌশল বিষয়ক প্রথম উচ্চশিক্ষা প্রতিষ্ঠান, যেখানে বিমান চলাচল ও মহাকাশ প্রযুক্তির ওপর বিশেষায়িত কোর্স করানো হয়",
    "link": "/aaub",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/AAUB.png"
  },
  {
    "nameBn": "ইসলামিক ইউনিভার্সিটি অব টেকনোলজি",
    "nameEn": "Islamic University of Technology",
    "shortName": "IUT",
    "id": "iut",
    "category": [
      "বিশেষ",
      "প্রকৌশল"
    ],
    "description": "এটি মূলত একটি শিক্ষা ও গবেষণা প্রতিষ্ঠান হিসেবে প্রতিষ্ঠা লাভ করেছিল এবং বর্তমানে বাংলাদেশের একমাত্র আন্তর্জাতিক প্রকৌশল বিশ্ববিদ্যালয় হিসেবে স্বীকৃত হয়েছে",
    "link": "/iut",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/IUT.png"
  },
  {
    "nameBn": "বাংলাদেশ টেক্সটাইল বিশ্ববিদ্যালয়",
    "nameEn": "Bangladesh University of Textiles",
    "shortName": "BUTEX",
    "id": "butex",
    "category": [
      "বিশেষ"
    ],
    "description": "টেক্সটাইল ইঞ্জিনিয়ারিং শিক্ষার জন্য দেশের একমাত্র সরকারি বিশ্ববিদ্যালয়।",
    "link": "/butex",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/BUTex.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "বাংলাদেশ ইউনিভার্সিটি অব প্রফেশনালস",
    "nameEn": "Bangladesh University of Professionals",
    "shortName": "BUP",
    "id": "bup",
    "category": [
      "বিশেষ"
    ],
    "description": "বাংলাদেশ সশস্ত্র বাহিনী দ্বারা পরিচালিত একটি মানসম্পন্ন শিক্ষা প্রতিষ্ঠান।",
    "link": "/bup",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/BUP.png",
    "admissionInfo": {},
    "historyAndMap": {},
    "links": [],
    "questionBanks": {},
    "subjects": {}
  },
  {
    "nameBn": "ইউনিভার্সিটি অফ ফ্রন্টিয়ার টেকনোলজি, বাংলাদেশ",
    "nameEn": "University of Frontier Technology, Bangladesh",
    "shortName": "UFTB",
    "id": "uftb",
    "category": [
      "বিশেষ"
    ],
    "description": "একটি বিশেষায়িত সরকারি বিশ্ববিদ্যালয় যা গাজীপুর জেলার কালিয়াকৈরে অবস্থিত এবং এটি প্রযুক্তি শিক্ষায় গ্লোবাল ট্রেন্ড অনুসরণ করে থাকে",
    "link": "/uftb",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/UFTB.png"
  },
  {
    "nameBn": "বাংলাদেশ মেরিটাইম বিশ্ববিদ্যালয়",
    "nameEn": "Bangladesh Maritime University",
    "shortName": "BMU",
    "id": "bmu",
    "category": [
      "বিশেষ"
    ],
    "description": "নীল অর্থনীতি (ব্লু ইকোনমি) অর্জনের লক্ষ্যে মেরিটাইম বিষয়ক উচ্চতর পড়াশুনার জন্য প্রতিষ্ঠিত বাংলাদেশের প্রথম 'বিশেষায়িত' বিশ্ববিদ্যালয় এটি এবং পাশাপাশি এখান থেকে মেরিন ক্যাডেটদের আন্তর্জাতিক মানসম্পন্ন 'ব্যাচেলর অব মেরিটাইম সায়েন্স' ডিগ্রি দেয়া হয়",
    "link": "/bmu",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/BMU.png"
  },
  {
    "nameBn": "জাতীয় বিশ্ববিদ্যালয়",
    "nameEn": "National University",
    "shortName": "NU",
    "id": "NU",
    "category": [
      "বিশেষ",
      "অধিভুক্ত",
      "গুচ্ছ"
    ],
    "description": "জাতীয় বিশ্ববিদ্যালয় বাংলাদেশের একটি পাবলিক কলেজিয়েট বিশ্ববিদ্যালয় যেখানে অধিভুক্ত ২৬৪টি সরকারি কলেজ ও নিজ ক্যাম্পাসে অনার্স প্রদান কার্যক্রম রয়েছে",
    "link": "/NU",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/NU.png"
  },
  {
    "nameBn": "ঢাকা কেন্দ্রীয় বিশ্ববিদ্যালয় (কলেজ)",
    "nameEn": "Dhaka Central University",
    "shortName": "DCU",
    "id": "DCU",
    "category": [
      "অধিভুক্ত",
      "গুচ্ছ"
    ],
    "description": "ঢাকা কেন্দ্রীয় বিশ্ববিদ্যালয় অধিভুক্ত ৭টি সরকারি কলেজ রয়েছে",
    "link": "/DCU",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/DCU.png"
  },
  {
    "nameBn": "ঢাকা বিশ্ববিদ্যালয় অধিভুক্ত",
    "nameEn": "Dhaka University Affiliated",
    "shortName": "DU-Affiliated",
    "id": "du-affiliated",
    "category": [
      "অধিভুক্ত"
    ],
    "description": "ঢাকা বিশ্ববিদ্যালয় অধিভুক্ত কলেজের প্রযুক্তি ও গার্হস্থ্য ইউনিট নিয়ে এখানে বিস্তারিত তথ্য আছে",
    "link": "/du-affiliated",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/DU.png"
  },
  {
    "nameBn": "বুটেক্স অধিভুক্ত",
    "nameEn": "BUTex Affiliated",
    "shortName": "BUTex-Affiliated",
    "id": "butex-affiliated",
    "category": [
      "অধিভুক্ত"
    ],
    "description": "বুটেক্স অধিভুক্ত সরকারি ১০ টেক্সটাইল ইঞ্জিনিয়ারিং কলেজ রয়েছে",
    "link": "/butex-affiliated",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/BUTex.png"
  },
  {
    "nameBn": "শাবিপ্রবি বা সাস্ট অধিভুক্ত",
    "nameEn": "SUST Affiliated",
    "shortName": "SUST-Affiliated",
    "id": "sust-affiliated",
    "category": [
      "অধিভুক্ত"
    ],
    "description": "শাহজালাল বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয় এর অধিভুক্ত একটি প্রকৌশল কলেজ রয়েছে যার নাম সিলেট ইঞ্জিনিয়ারিং কলেজ",
    "link": "/sust-affiliated",
    "logo": "https://raw.githubusercontent.com/MNRfrom2020/logo-and-icon-cdn/refs/heads/main/University/SUST.png"
  },
  {
    "nameBn": "আহসানউল্লাহ বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "nameEn": "Ahsanullah University of Science and Technology",
    "shortName": "AUST",
    "id": "aust",
    "category": [
      "প্রাইভেট"
    ],
    "description": "দেশের অন্যতম সেরা একটি বেসরকারি প্রকৌশল বিশ্ববিদ্যালয়।",
    "link": "/aust",
    "logo": "https://upload.wikimedia.org/wikipedia/en/a/ac/Ahsanullah_University_of_Science_and_Technology_Logo.svg"
  }
];
